import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

interface ManifestEntry {
  id: string;
  src: string;
  path: string;
  kind: "image";
  license: "CC0" | "CC-BY-4.0";
  source: string;
  originality: string;
  date: string;
}

interface RegionArt {
  id: string;
  sky: string;
  horizon: string;
  near: string;
  accent: string;
}

interface RoadsideProp {
  id: string;
  category: "tree" | "sign" | "barrier" | "building";
}

const ROOT = process.cwd();
const MANIFEST_PATH = path.join(ROOT, "public", "art.manifest.json");
const GENERATED_DATE = "2026-04-29";
const SOURCE = "agent-authored placeholder generated by scripts/generate-placeholder-art.ts";
const ORIGINALITY =
  "Original geometric placeholder art authored for VibeGear2. It does not trace or copy a commercial game asset, real vehicle, logo, or manufacturer design.";

const REGIONS: readonly RegionArt[] = [
  { id: "velvet-coast", sky: "#17325c", horizon: "#2f6f54", near: "#285d2b", accent: "#9cc9ff" },
  { id: "iron-borough", sky: "#1d2937", horizon: "#535b60", near: "#343a40", accent: "#f5cf69" },
  { id: "ember-steppe", sky: "#40263b", horizon: "#9b4b32", near: "#5f3d22", accent: "#ffba6b" },
  { id: "breakwater-isles", sky: "#12304a", horizon: "#326a84", near: "#1f5e45", accent: "#a7e3ff" },
  { id: "glass-ridge", sky: "#223a56", horizon: "#8da8bc", near: "#4e6b7b", accent: "#d8f4ff" },
  { id: "neon-meridian", sky: "#151833", horizon: "#4c3d79", near: "#22324f", accent: "#ff5bd6" },
  { id: "moss-frontier", sky: "#17352b", horizon: "#37694b", near: "#204f32", accent: "#c2e879" },
  { id: "crown-circuit", sky: "#1c2345", horizon: "#55608a", near: "#2e355b", accent: "#ffd85a" },
];

const CAR_SHEETS = [
  { id: "sparrow_gt", body: "#f2c94c", glass: "#18243d", trim: "#111827", accent: "#ffe56e" },
  { id: "breaker_s", body: "#d94f3f", glass: "#172033", trim: "#22191a", accent: "#ffb17a" },
  { id: "vanta_xr", body: "#5d6ce1", glass: "#101a34", trim: "#141827", accent: "#a7e3ff" },
  { id: "tempest_r", body: "#4bd77f", glass: "#142636", trim: "#102018", accent: "#d8ff6b" },
  { id: "bastion_lm", body: "#d7dde6", glass: "#1f2b3a", trim: "#32363d", accent: "#f5d45f" },
  { id: "nova_shade", body: "#5b4bd7", glass: "#14182b", trim: "#171326", accent: "#ff5bd6" },
] as const;

const HUD_ICONS = [
  "cash",
  "repair",
  "engine",
  "gearbox",
  "dry-tire",
  "wet-tire",
  "nitro",
  "armor",
  "visibility",
  "grip",
  "tour-standings",
] as const;

const EFFECTS = ["flash", "dust", "sparks", "rain", "fog", "snow"] as const;

const MENU_BACKGROUNDS = [
  { id: "title", region: "crown-circuit", label: "TITLE", accent: "#ffd85a" },
  { id: "world", region: "velvet-coast", label: "WORLD", accent: "#9cc9ff" },
  { id: "garage", region: "iron-borough", label: "GARAGE", accent: "#f5cf69" },
  { id: "race-prep", region: "neon-meridian", label: "PREP", accent: "#ff5bd6" },
  { id: "results", region: "glass-ridge", label: "RESULTS", accent: "#d8f4ff" },
  { id: "daily", region: "ember-steppe", label: "DAILY", accent: "#ffba6b" },
  { id: "options", region: "moss-frontier", label: "OPTIONS", accent: "#c2e879" },
  { id: "loading", region: "breakwater-isles", label: "LOADING", accent: "#a7e3ff" },
] as const;

const ROADSIDE_PROPS: readonly RoadsideProp[] = [
  { id: "marker-light", category: "sign" },
  { id: "speed-board", category: "sign" },
  { id: "chevron-left", category: "sign" },
  { id: "chevron-right", category: "sign" },
  { id: "short-rail", category: "barrier" },
  { id: "long-rail", category: "barrier" },
  { id: "tire-stack", category: "barrier" },
  { id: "cone-row", category: "barrier" },
  { id: "slim-tree", category: "tree" },
  { id: "wide-tree", category: "tree" },
  { id: "low-building", category: "building" },
  { id: "tower-building", category: "building" },
] as const;

const manifest: ManifestEntry[] = [
  {
    id: "sparrow-car-sprite-atlas",
    src: "/art/cars/sparrow.svg",
    path: "art/cars/sparrow.svg",
    kind: "image",
    license: "CC-BY-4.0",
    source: "original by VibeGear2 project contributors in this repository",
    originality:
      "Original stylized compact sports coupe sprite sheet drawn for VibeGear2 on 2026-04-27. It uses simple geometric shapes and does not trace or copy a commercial game asset, real vehicle, logo, or manufacturer design.",
    date: "2026-04-27",
  },
];

function writeTextFile(relPath: string, contents: string): void {
  const abs = path.join(ROOT, relPath);
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, contents, "utf8");
}

function addManifest(id: string, relPath: string): void {
  manifest.push({
    id,
    src: "/" + relPath,
    path: relPath,
    kind: "image",
    license: "CC0",
    source: SOURCE,
    originality: ORIGINALITY,
    date: GENERATED_DATE,
  });
}

function svg(width: number, height: number, body: string): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="VibeGear2 placeholder art">`,
    body,
    "</svg>",
    "",
  ].join("\n");
}

function backdropSvg(region: RegionArt, layer: "sky" | "mountains" | "hills"): string {
  if (layer === "sky") {
    return svg(
      1920,
      540,
      [
        `<rect width="1920" height="540" fill="${region.sky}"/>`,
        `<path d="M0 270 L220 120 L430 270 L650 150 L900 270 L1160 110 L1390 270 L1660 130 L1920 250 L1920 540 L0 540 Z" fill="${region.horizon}" opacity="0.55"/>`,
        `<rect x="0" y="505" width="1920" height="35" fill="${region.accent}" opacity="0.18"/>`,
      ].join("\n"),
    );
  }
  if (layer === "mountains") {
    return svg(
      1920,
      220,
      [
        `<rect width="1920" height="220" fill="none"/>`,
        `<path d="M0 190 L150 90 L300 190 L500 70 L760 190 L970 85 L1220 190 L1460 60 L1740 190 L1920 105 L1920 220 L0 220 Z" fill="${region.horizon}"/>`,
        `<path d="M0 205 C260 170 470 200 690 165 C920 130 1120 180 1340 145 C1580 115 1740 165 1920 130 L1920 220 L0 220 Z" fill="${region.near}" opacity="0.62"/>`,
      ].join("\n"),
    );
  }
  return svg(
    1920,
    180,
    [
      `<rect width="1920" height="180" fill="none"/>`,
      `<path d="M0 120 C210 92 360 124 530 105 C720 82 880 128 1080 98 C1310 66 1500 118 1680 92 C1810 74 1880 82 1920 76 L1920 180 L0 180 Z" fill="${region.near}"/>`,
      `<rect x="0" y="154" width="1920" height="26" fill="${region.accent}" opacity="0.22"/>`,
    ].join("\n"),
  );
}

function roadsideSvg(): string {
  return svg(
    512,
    256,
    [
      '<rect width="512" height="256" fill="none"/>',
      '<rect x="6" y="8" width="20" height="54" fill="#d7dde6"/>',
      '<rect x="2" y="0" width="28" height="12" fill="#fff275"/>',
      '<rect x="42" y="8" width="20" height="54" fill="#d7dde6"/>',
      '<rect x="38" y="0" width="28" height="12" fill="#fff275"/>',
      '<path d="M96 8 L62 96 L132 96 Z" fill="#1f7a45"/>',
      '<rect x="92" y="72" width="8" height="24" fill="#6b4a2e"/>',
      '<path d="M160 2 L124 96 L198 96 Z" fill="#2f8a52"/>',
      '<rect x="156" y="72" width="8" height="24" fill="#6b4a2e"/>',
      '<path d="M224 12 L190 96 L260 96 Z" fill="#1d6e3b"/>',
      '<rect x="220" y="72" width="8" height="24" fill="#6b4a2e"/>',
      '<rect x="0" y="104" width="14" height="24" fill="#c4cad3"/>',
      '<rect x="34" y="110" width="42" height="18" fill="#8e9299"/>',
      '<rect x="82" y="106" width="42" height="22" fill="#7b8087"/>',
      '<rect x="260" y="0" width="10" height="128" fill="#d7dde6"/>',
      '<rect x="248" y="0" width="34" height="10" fill="#fff275"/>',
      '<rect x="310" y="42" width="76" height="58" fill="#45515c"/>',
      '<rect x="322" y="54" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="350" y="54" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="328" y="76" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="358" y="76" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="410" y="72" width="88" height="18" fill="#bdc3ca"/>',
      '<rect x="418" y="88" width="12" height="40" fill="#bdc3ca"/>',
      '<rect x="478" y="88" width="12" height="40" fill="#bdc3ca"/>',
    ].join("\n"),
  );
}

function roadsidePropSvg(region: RegionArt, prop: RoadsideProp, index: number): string {
  const base = [
    '<rect width="128" height="128" fill="none"/>',
    '<ellipse cx="64" cy="116" rx="42" ry="8" fill="#10151f" opacity="0.35"/>',
  ];
  if (prop.category === "sign") {
    const arrow = prop.id.includes("left")
      ? '<path d="M76 43 L48 64 L76 85" fill="none" stroke="#101827" stroke-width="10" stroke-linecap="square" stroke-linejoin="miter"/>'
      : '<path d="M52 43 L80 64 L52 85" fill="none" stroke="#101827" stroke-width="10" stroke-linecap="square" stroke-linejoin="miter"/>';
    return svg(
      128,
      128,
      [
        ...base,
        '<rect x="59" y="62" width="10" height="50" fill="#d7dde6"/>',
        `<rect x="28" y="22" width="72" height="44" rx="3" fill="${region.accent}"/>`,
        prop.id.includes("chevron") ? arrow : '<rect x="42" y="38" width="44" height="12" fill="#101827"/>',
        `<text x="64" y="123" text-anchor="middle" font-family="monospace" font-size="8" fill="${region.accent}">PLACEHOLDER</text>`,
      ].join("\n"),
    );
  }
  if (prop.category === "barrier") {
    const railWidth = prop.id === "long-rail" ? 96 : 64;
    const x = (128 - railWidth) / 2;
    return svg(
      128,
      128,
      [
        ...base,
        `<rect x="${x}" y="72" width="${railWidth}" height="12" fill="#d7dde6"/>`,
        `<rect x="${x}" y="90" width="${railWidth}" height="10" fill="${region.accent}"/>`,
        '<rect x="34" y="68" width="8" height="42" fill="#b7c0ca"/>',
        '<rect x="86" y="68" width="8" height="42" fill="#b7c0ca"/>',
        prop.id === "tire-stack"
          ? '<circle cx="44" cy="74" r="13" fill="#161b22"/><circle cx="64" cy="74" r="13" fill="#161b22"/><circle cx="84" cy="74" r="13" fill="#161b22"/>'
          : "",
        prop.id === "cone-row"
          ? '<path d="M38 98 L48 66 L58 98 Z" fill="#ff7a1a"/><path d="M60 98 L70 66 L80 98 Z" fill="#ff7a1a"/><path d="M82 98 L92 66 L102 98 Z" fill="#ff7a1a"/>'
          : "",
        `<text x="64" y="123" text-anchor="middle" font-family="monospace" font-size="8" fill="${region.accent}">PLACEHOLDER</text>`,
      ].join("\n"),
    );
  }
  if (prop.category === "tree") {
    const leaf = prop.id === "wide-tree" ? 32 : 24;
    return svg(
      128,
      128,
      [
        ...base,
        '<rect x="59" y="72" width="10" height="40" fill="#6b4a2e"/>',
        `<path d="M64 16 L${64 - leaf} 88 L${64 + leaf} 88 Z" fill="${region.near}"/>`,
        `<path d="M64 8 L${70 - leaf} 66 L${58 + leaf} 66 Z" fill="${region.horizon}" opacity="0.9"/>`,
        `<rect x="${48 + (index % 4) * 2}" y="68" width="10" height="6" fill="${region.accent}" opacity="0.35"/>`,
        `<text x="64" y="123" text-anchor="middle" font-family="monospace" font-size="8" fill="${region.accent}">PLACEHOLDER</text>`,
      ].join("\n"),
    );
  }
  const isTower = prop.id === "tower-building";
  const buildingTop = isTower ? 24 : 56;
  const innerTop = buildingTop + 6;
  const buildingHeight = isTower ? 88 : 56;
  const innerHeight = buildingHeight - 12;
  const floors = isTower ? 4 : 2;
  const windows = Array.from({ length: floors * 2 }, (_, i) => {
    const x = 46 + (i % 2) * 24;
    const y = innerTop + 10 + Math.floor(i / 2) * 16;
    return `<rect x="${x}" y="${y}" width="12" height="8" fill="${region.accent}" opacity="0.65"/>`;
  });
  return svg(
    128,
    128,
    [
      ...base,
      `<rect x="34" y="${buildingTop}" width="60" height="${buildingHeight}" fill="${region.horizon}"/>`,
      `<rect x="40" y="${innerTop}" width="48" height="${innerHeight}" fill="${region.near}" opacity="0.82"/>`,
      ...windows,
      `<text x="64" y="123" text-anchor="middle" font-family="monospace" font-size="8" fill="${region.accent}">PLACEHOLDER</text>`,
    ].join("\n"),
  );
}

function carSheetSvg(car: (typeof CAR_SHEETS)[number]): string {
  const skews = [0, 4, 8, 12, 8, 4, 0, -4, -8, -12, -8, -4];
  const damageRows = [
    { y: 16, id: "clean", extra: "" },
    {
      y: 48,
      id: "dented",
      extra: `<path d="M-23 -1 L-17 4 L-21 7" fill="none" stroke="${car.accent}" stroke-width="2" opacity="0.8"/>`,
    },
    {
      y: 80,
      id: "battered",
      extra: `<path d="M-24 -2 L-15 5 L-23 8" fill="none" stroke="${car.trim}" stroke-width="2"/><path d="M14 -4 L22 1 L18 7" fill="none" stroke="${car.trim}" stroke-width="2"/>`,
    },
  ];
  const dentedExtra = damageRows.find((row) => row.id === "dented")?.extra ?? "";
  const batteredExtra = damageRows.find((row) => row.id === "battered")?.extra ?? "";
  const frames: string[] = [];
  for (const row of damageRows) {
    for (let i = 0; i < skews.length; i += 1) {
      frames.push(
        `<g transform="translate(${32 + i * 64} ${row.y}) skewX(${skews[i]})"><use href="#shadow"/><use href="#${row.id}"/></g>`,
      );
    }
  }
  return svg(
    768,
    384,
    [
      '<rect width="768" height="384" fill="none"/>',
      '<defs>',
      '<g id="shadow"><ellipse cx="0" cy="13" rx="29" ry="5" fill="#10151f" opacity="0.55"/></g>',
      `<g id="clean"><path d="M-27 12 L27 12 L21 -8 L12 -14 L-12 -14 L-21 -8 Z" fill="${car.body}"/><path d="M-14 -7 L14 -7 L9 4 L-9 4 Z" fill="${car.glass}"/><path d="M-22 7 L-12 7 L-12 11 L-22 11 Z" fill="#ff3d38"/><path d="M12 7 L22 7 L22 11 L12 11 Z" fill="#ff3d38"/><path d="M-24 12 L-18 15 L18 15 L24 12 Z" fill="${car.trim}"/><path d="M-18 -5 L18 -5" stroke="${car.accent}" stroke-width="2"/></g>`,
      `<g id="dented"><use href="#clean"/>${dentedExtra}<rect x="13" y="7" width="9" height="4" fill="#d72f31"/></g>`,
      `<g id="battered"><use href="#clean"/>${batteredExtra}<rect x="-22" y="7" width="10" height="4" fill="#b83232"/><rect x="13" y="7" width="9" height="4" fill="#b83232"/></g>`,
      '<g id="brake"><use href="#clean"/><rect x="-24" y="6" width="13" height="6" fill="#ff4a44"/><rect x="11" y="6" width="13" height="6" fill="#ff4a44"/></g>',
      '<g id="nitro"><use href="#clean"/><path d="M-14 15 L0 26 L14 15 Z" fill="#44d7ff" opacity="0.75"/><path d="M-8 15 L0 23 L8 15 Z" fill="#e75cff" opacity="0.8"/></g>',
      "</defs>",
      ...frames,
      '<g transform="translate(32 112)"><use href="#shadow"/><use href="#brake"/></g>',
      '<g transform="translate(96 112)"><use href="#shadow"/><use href="#nitro"/></g>',
      `<text x="704" y="360" text-anchor="middle" font-family="monospace" font-size="16" font-weight="700" fill="${car.accent}">PLACEHOLDER</text>`,
    ].join("\n"),
  );
}

function hudIconSvg(id: string): string {
  const label = id.slice(0, 2).toUpperCase();
  return svg(
    64,
    64,
    [
      '<rect x="4" y="4" width="56" height="56" rx="6" fill="#101827"/>',
      '<rect x="8" y="8" width="48" height="48" rx="4" fill="#26364d"/>',
      '<circle cx="32" cy="29" r="14" fill="#f5d45f"/>',
      `<text x="32" y="38" text-anchor="middle" font-family="monospace" font-size="16" font-weight="700" fill="#101827">${label}</text>`,
    ].join("\n"),
  );
}

function effectSvg(effect: string): string {
  return svg(
    256,
    256,
    [
      '<rect width="256" height="256" fill="none"/>',
      '<circle cx="64" cy="64" r="42" fill="#ffffff" opacity="0.38"/>',
      '<circle cx="144" cy="82" r="28" fill="#f5d45f" opacity="0.55"/>',
      '<path d="M42 184 C82 142 118 218 162 162 C184 135 204 148 226 124" fill="none" stroke="#dce8f5" stroke-width="14" stroke-linecap="round" opacity="0.72"/>',
      `<text x="128" y="235" text-anchor="middle" font-family="monospace" font-size="18" font-weight="700" fill="#ffffff">${effect.toUpperCase()}</text>`,
    ].join("\n"),
  );
}

function menuBackgroundSvg(menu: (typeof MENU_BACKGROUNDS)[number]): string {
  const region = REGIONS.find((entry) => entry.id === menu.region);
  if (region === undefined) throw new Error(`Unknown menu background region: ${menu.region}`);
  return svg(
    1920,
    1080,
    [
      `<rect width="1920" height="1080" fill="${region.sky}"/>`,
      `<path d="M0 340 L220 160 L420 340 L690 185 L940 340 L1180 140 L1410 340 L1660 180 L1920 300 L1920 520 L0 520 Z" fill="${region.horizon}" opacity="0.6"/>`,
      `<path d="M0 470 C260 420 500 486 730 430 C1020 360 1230 460 1460 410 C1670 365 1800 405 1920 370 L1920 650 L0 650 Z" fill="${region.near}" opacity="0.78"/>`,
      '<rect x="0" y="640" width="1920" height="440" fill="#0b1019" opacity="0.45"/>',
      `<path d="M760 1080 L910 650 L1010 650 L1160 1080 Z" fill="#535b60" opacity="0.8"/>`,
      `<path d="M928 1080 L955 650 L965 650 L992 1080 Z" fill="${menu.accent}" opacity="0.75"/>`,
      `<rect x="116" y="116" width="480" height="18" fill="${menu.accent}" opacity="0.7"/>`,
      `<rect x="116" y="156" width="320" height="10" fill="${menu.accent}" opacity="0.32"/>`,
      `<rect x="1324" y="812" width="360" height="18" fill="${menu.accent}" opacity="0.45"/>`,
      `<text x="960" y="1000" text-anchor="middle" font-family="monospace" font-size="44" font-weight="700" fill="${menu.accent}" opacity="0.82">${menu.label} PLACEHOLDER</text>`,
    ].join("\n"),
  );
}

for (const region of REGIONS) {
  for (const layer of ["sky", "mountains", "hills"] as const) {
    const relPath = `public/art/backdrops/${region.id}/${layer}.svg`;
    writeTextFile(relPath, backdropSvg(region, layer));
    addManifest(`backdrop:${region.id}:${layer}`, relPath.slice("public/".length));
  }
}

for (const car of CAR_SHEETS) {
  const relPath = `public/art/cars/${car.id}.svg`;
  writeTextFile(relPath, carSheetSvg(car));
  addManifest(`car:${car.id}:sprite-sheet`, relPath.slice("public/".length));
}

writeTextFile("public/art/roadside/temperate.svg", roadsideSvg());
addManifest("roadside:temperate", "art/roadside/temperate.svg");

for (const region of REGIONS) {
  for (const [i, prop] of ROADSIDE_PROPS.entries()) {
    const relPath = `public/art/roadside/${region.id}/${prop.id}.svg`;
    writeTextFile(relPath, roadsidePropSvg(region, prop, i));
    addManifest(`roadside:${region.id}:${prop.id}`, relPath.slice("public/".length));
  }
}

for (const icon of HUD_ICONS) {
  const relPath = `public/art/hud/${icon}.svg`;
  writeTextFile(relPath, hudIconSvg(icon));
  addManifest(`hud:${icon}`, relPath.slice("public/".length));
}

for (const effect of EFFECTS) {
  const relPath = `public/art/effects/${effect}.svg`;
  writeTextFile(relPath, effectSvg(effect));
  addManifest(`effect:${effect}`, relPath.slice("public/".length));
}

for (const menu of MENU_BACKGROUNDS) {
  const relPath = `public/art/menu/${menu.id}.svg`;
  writeTextFile(relPath, menuBackgroundSvg(menu));
  addManifest(`menu:${menu.id}:background`, relPath.slice("public/".length));
}

manifest.sort((a, b) => a.src.localeCompare(b.src));
writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + "\n", "utf8");
