import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

interface ManifestEntry {
  id: string;
  src: string;
  path: string;
  kind: "image";
  license: "CC0" | "CC-BY-4.0";
  source: string;
  originality: string;
  date: string;
}

interface RegionArt {
  id: string;
  sky: string;
  horizon: string;
  near: string;
  accent: string;
}

interface RoadsideProp {
  id: string;
  category: "tree" | "sign" | "barrier" | "building";
}

interface CarSheet {
  id: string;
  name: string;
  body: string;
  glass: string;
  trim: string;
  accent: string;
  secondary: string;
  stripe: string;
  nose: "pointed" | "blunt" | "wide" | "wedge";
  tail: "compact" | "fastback" | "wide" | "long";
  wing: "none" | "ducktail" | "blade" | "enduro";
  stance: "narrow" | "balanced" | "wide";
}

const ROOT = process.cwd();
const MANIFEST_PATH = path.join(ROOT, "public", "art.manifest.json");
const GENERATED_DATE = "2026-04-29";
const SOURCE = "agent-authored placeholder generated by scripts/generate-placeholder-art.ts";
const ORIGINALITY =
  "Original geometric placeholder art authored for VibeGear2. It does not trace or copy a commercial game asset, real vehicle, logo, or manufacturer design.";
const CAR_SOURCE = "agent-authored production car sheets generated by scripts/generate-placeholder-art.ts";
const CAR_ORIGINALITY =
  "Original stylized car sprite sheets authored for VibeGear2. They use fictional compact sports-coupe silhouettes, hand-tuned geometric decals, and no traced commercial game asset, real vehicle, logo, or manufacturer design.";
const ROADSIDE_SOURCE =
  "agent-authored production roadside prop set generated by scripts/generate-placeholder-art.ts";
const ROADSIDE_ORIGINALITY =
  "Original stylized roadside prop art authored for VibeGear2. The signs, barriers, trees, and buildings use fictional regional shape language and no traced commercial game asset, real venue, logo, or manufacturer design.";
const MENU_SOURCE = "agent-authored production menu scenes generated by scripts/generate-placeholder-art.ts";
const MENU_ORIGINALITY =
  "Original stylized menu scene art authored for VibeGear2. The garage bays, tour map, race prep lane, results podium, daily marker, options pit, and loading convoy are fictional compositions with no traced commercial game asset, real venue, logo, or manufacturer design.";

const REGIONS: readonly RegionArt[] = [
  { id: "velvet-coast", sky: "#17325c", horizon: "#2f6f54", near: "#285d2b", accent: "#9cc9ff" },
  { id: "iron-borough", sky: "#1d2937", horizon: "#535b60", near: "#343a40", accent: "#f5cf69" },
  { id: "ember-steppe", sky: "#40263b", horizon: "#9b4b32", near: "#5f3d22", accent: "#ffba6b" },
  { id: "breakwater-isles", sky: "#12304a", horizon: "#326a84", near: "#1f5e45", accent: "#a7e3ff" },
  { id: "glass-ridge", sky: "#223a56", horizon: "#8da8bc", near: "#4e6b7b", accent: "#d8f4ff" },
  { id: "neon-meridian", sky: "#151833", horizon: "#4c3d79", near: "#22324f", accent: "#ff5bd6" },
  { id: "moss-frontier", sky: "#17352b", horizon: "#37694b", near: "#204f32", accent: "#c2e879" },
  { id: "crown-circuit", sky: "#1c2345", horizon: "#55608a", near: "#2e355b", accent: "#ffd85a" },
];

const CAR_SHEETS: readonly CarSheet[] = [
  {
    id: "sparrow_gt",
    name: "Sparrow GT",
    body: "#f2c94c",
    glass: "#18243d",
    trim: "#111827",
    accent: "#fff07a",
    secondary: "#d9a92e",
    stripe: "#f8f1d2",
    nose: "pointed",
    tail: "compact",
    wing: "ducktail",
    stance: "balanced",
  },
  {
    id: "breaker_s",
    name: "Breaker S",
    body: "#d94f3f",
    glass: "#172033",
    trim: "#22191a",
    accent: "#ffb17a",
    secondary: "#772c2c",
    stripe: "#ffe3a6",
    nose: "wide",
    tail: "fastback",
    wing: "blade",
    stance: "wide",
  },
  {
    id: "vanta_xr",
    name: "Vanta XR",
    body: "#5d6ce1",
    glass: "#101a34",
    trim: "#141827",
    accent: "#a7e3ff",
    secondary: "#2d378e",
    stripe: "#d9f5ff",
    nose: "wedge",
    tail: "compact",
    wing: "none",
    stance: "narrow",
  },
  {
    id: "tempest_r",
    name: "Tempest R",
    body: "#4bd77f",
    glass: "#142636",
    trim: "#102018",
    accent: "#d8ff6b",
    secondary: "#19824f",
    stripe: "#efffd0",
    nose: "pointed",
    tail: "fastback",
    wing: "ducktail",
    stance: "balanced",
  },
  {
    id: "bastion_lm",
    name: "Bastion LM",
    body: "#d7dde6",
    glass: "#1f2b3a",
    trim: "#32363d",
    accent: "#f5d45f",
    secondary: "#8c939d",
    stripe: "#fff6c9",
    nose: "blunt",
    tail: "long",
    wing: "enduro",
    stance: "wide",
  },
  {
    id: "nova_shade",
    name: "Nova Shade",
    body: "#5b4bd7",
    glass: "#14182b",
    trim: "#171326",
    accent: "#ff5bd6",
    secondary: "#2c1f78",
    stripe: "#f2dcff",
    nose: "wedge",
    tail: "wide",
    wing: "blade",
    stance: "wide",
  },
] as const;

const HUD_ICONS = [
  "cash",
  "repair",
  "engine",
  "gearbox",
  "dry-tire",
  "wet-tire",
  "nitro",
  "armor",
  "visibility",
  "grip",
  "tour-standings",
] as const;

const EFFECTS = ["flash", "dust", "sparks", "rain", "fog", "snow"] as const;

const MENU_BACKGROUNDS = [
  { id: "title", region: "crown-circuit", label: "TITLE" },
  { id: "world", region: "velvet-coast", label: "WORLD" },
  { id: "garage", region: "iron-borough", label: "GARAGE" },
  { id: "race-prep", region: "neon-meridian", label: "RACE PREP" },
  { id: "results", region: "glass-ridge", label: "RESULTS" },
  { id: "daily", region: "ember-steppe", label: "DAILY" },
  { id: "options", region: "moss-frontier", label: "OPTIONS" },
  { id: "loading", region: "breakwater-isles", label: "LOADING" },
] as const;
type MenuBackgroundId = (typeof MENU_BACKGROUNDS)[number]["id"];

const ROADSIDE_PROPS: readonly RoadsideProp[] = [
  { id: "marker-light", category: "sign" },
  { id: "speed-board", category: "sign" },
  { id: "chevron-left", category: "sign" },
  { id: "chevron-right", category: "sign" },
  { id: "short-rail", category: "barrier" },
  { id: "long-rail", category: "barrier" },
  { id: "tire-stack", category: "barrier" },
  { id: "cone-row", category: "barrier" },
  { id: "slim-tree", category: "tree" },
  { id: "wide-tree", category: "tree" },
  { id: "low-building", category: "building" },
  { id: "tower-building", category: "building" },
] as const;

const manifest: ManifestEntry[] = [
  {
    id: "sparrow-car-sprite-atlas",
    src: "/art/cars/sparrow.svg",
    path: "art/cars/sparrow.svg",
    kind: "image",
    license: "CC-BY-4.0",
    source: CAR_SOURCE,
    originality: CAR_ORIGINALITY,
    date: GENERATED_DATE,
  },
];

function writeTextFile(relPath: string, contents: string): void {
  const abs = path.join(ROOT, relPath);
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, contents, "utf8");
}

function addManifest(
  id: string,
  relPath: string,
  details: Partial<Pick<ManifestEntry, "license" | "source" | "originality" | "date">> = {},
): void {
  manifest.push({
    id,
    src: "/" + relPath,
    path: relPath,
    kind: "image",
    license: details.license ?? "CC0",
    source: details.source ?? SOURCE,
    originality: details.originality ?? ORIGINALITY,
    date: details.date ?? GENERATED_DATE,
  });
}

function svg(
  width: number,
  height: number,
  body: string,
  label = "VibeGear2 placeholder art",
): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${label}">`,
    body,
    "</svg>",
    "",
  ].join("\n");
}

function backdropSvg(region: RegionArt, layer: "sky" | "mountains" | "hills"): string {
  if (layer === "sky") {
    return svg(
      1920,
      540,
      [
        `<rect width="1920" height="540" fill="${region.sky}"/>`,
        `<path d="M0 270 L220 120 L430 270 L650 150 L900 270 L1160 110 L1390 270 L1660 130 L1920 250 L1920 540 L0 540 Z" fill="${region.horizon}" opacity="0.55"/>`,
        `<rect x="0" y="505" width="1920" height="35" fill="${region.accent}" opacity="0.18"/>`,
      ].join("\n"),
    );
  }
  if (layer === "mountains") {
    return svg(
      1920,
      220,
      [
        `<rect width="1920" height="220" fill="none"/>`,
        `<path d="M0 190 L150 90 L300 190 L500 70 L760 190 L970 85 L1220 190 L1460 60 L1740 190 L1920 105 L1920 220 L0 220 Z" fill="${region.horizon}"/>`,
        `<path d="M0 205 C260 170 470 200 690 165 C920 130 1120 180 1340 145 C1580 115 1740 165 1920 130 L1920 220 L0 220 Z" fill="${region.near}" opacity="0.62"/>`,
      ].join("\n"),
    );
  }
  return svg(
    1920,
    180,
    [
      `<rect width="1920" height="180" fill="none"/>`,
      `<path d="M0 120 C210 92 360 124 530 105 C720 82 880 128 1080 98 C1310 66 1500 118 1680 92 C1810 74 1880 82 1920 76 L1920 180 L0 180 Z" fill="${region.near}"/>`,
      `<rect x="0" y="154" width="1920" height="26" fill="${region.accent}" opacity="0.22"/>`,
    ].join("\n"),
  );
}

function roadsideSvg(): string {
  return svg(
    512,
    256,
    [
      '<rect width="512" height="256" fill="none"/>',
      '<rect x="6" y="8" width="20" height="54" fill="#404040"/>',
      '<rect x="2" y="0" width="28" height="12" fill="#202020"/>',
      '<rect x="42" y="8" width="20" height="54" fill="#404040"/>',
      '<rect x="38" y="0" width="28" height="12" fill="#202020"/>',
      '<path d="M96 8 L62 96 L132 96 Z" fill="#606060"/>',
      '<rect x="92" y="72" width="8" height="24" fill="#404040"/>',
      '<path d="M160 2 L124 96 L198 96 Z" fill="#808080"/>',
      '<rect x="156" y="72" width="8" height="24" fill="#404040"/>',
      '<path d="M224 12 L190 96 L260 96 Z" fill="#606060"/>',
      '<rect x="220" y="72" width="8" height="24" fill="#404040"/>',
      '<rect x="0" y="104" width="14" height="24" fill="#404040"/>',
      '<rect x="34" y="110" width="42" height="18" fill="#a0a0a0"/>',
      '<rect x="82" y="106" width="42" height="22" fill="#a0a0a0"/>',
      '<rect x="260" y="0" width="10" height="128" fill="#404040"/>',
      '<rect x="248" y="0" width="34" height="10" fill="#202020"/>',
      '<rect x="310" y="42" width="76" height="58" fill="#a0a0a0"/>',
      '<rect x="322" y="54" width="14" height="12" fill="#e0e0e0"/>',
      '<rect x="350" y="54" width="14" height="12" fill="#e0e0e0"/>',
      '<rect x="328" y="76" width="14" height="12" fill="#e0e0e0"/>',
      '<rect x="358" y="76" width="14" height="12" fill="#e0e0e0"/>',
      '<rect x="410" y="72" width="88" height="18" fill="#c0c0c0"/>',
      '<rect x="418" y="88" width="12" height="40" fill="#c0c0c0"/>',
      '<rect x="478" y="88" width="12" height="40" fill="#c0c0c0"/>',
    ].join("\n"),
    "temperate roadside production atlas",
  );
}

function propAccentMark(region: RegionArt, index: number): string {
  const x = 24 + ((index * 13) % 52);
  return `<rect x="${x}" y="102" width="28" height="5" fill="${region.accent}" opacity="0.45"/>`;
}

function roadsidePropSvg(region: RegionArt, prop: RoadsideProp, index: number): string {
  const base = [
    '<rect width="128" height="128" fill="none"/>',
    '<ellipse cx="64" cy="116" rx="42" ry="8" fill="#10151f" opacity="0.35"/>',
  ];
  if (prop.category === "sign") {
    const arrow = prop.id.includes("left")
      ? '<path d="M76 43 L48 64 L76 85" fill="none" stroke="#101827" stroke-width="10" stroke-linecap="square" stroke-linejoin="miter"/>'
      : '<path d="M52 43 L80 64 L52 85" fill="none" stroke="#101827" stroke-width="10" stroke-linecap="square" stroke-linejoin="miter"/>';
    const panel =
      prop.id === "marker-light"
        ? `<circle cx="64" cy="43" r="14" fill="${region.accent}"/><circle cx="64" cy="43" r="6" fill="#ffffff" opacity="0.72"/>`
        : prop.id === "speed-board"
          ? `<rect x="38" y="36" width="52" height="14" fill="#101827"/><rect x="44" y="54" width="40" height="6" fill="${region.near}" opacity="0.75"/>`
          : arrow;
    return svg(
      128,
      128,
      [
        ...base,
        '<rect x="59" y="61" width="10" height="51" fill="#d7dde6"/>',
        `<rect x="56" y="62" width="4" height="50" fill="${region.horizon}" opacity="0.5"/>`,
        `<rect x="28" y="22" width="72" height="44" rx="3" fill="${region.accent}"/>`,
        `<rect x="32" y="26" width="64" height="36" rx="2" fill="${region.accent}" opacity="0.62"/>`,
        panel,
        propAccentMark(region, index),
      ].join("\n"),
      `${region.id} ${prop.id} roadside prop`,
    );
  }
  if (prop.category === "barrier") {
    const railWidth = prop.id === "long-rail" ? 96 : 64;
    const x = (128 - railWidth) / 2;
    const barrierBody =
      prop.id === "tire-stack"
        ? '<circle cx="40" cy="75" r="14" fill="#161b22"/><circle cx="62" cy="75" r="14" fill="#161b22"/><circle cx="84" cy="75" r="14" fill="#161b22"/><circle cx="51" cy="91" r="14" fill="#161b22"/><circle cx="73" cy="91" r="14" fill="#161b22"/>'
        : prop.id === "cone-row"
          ? '<path d="M32 100 L44 62 L56 100 Z" fill="#ff7a1a"/><path d="M58 100 L70 62 L82 100 Z" fill="#ff7a1a"/><path d="M84 100 L96 62 L108 100 Z" fill="#ff7a1a"/><rect x="36" y="82" width="16" height="5" fill="#fff3d8"/><rect x="62" y="82" width="16" height="5" fill="#fff3d8"/><rect x="88" y="82" width="16" height="5" fill="#fff3d8"/>'
          : `<rect x="${x}" y="70" width="${railWidth}" height="12" fill="#d7dde6"/><rect x="${x}" y="88" width="${railWidth}" height="10" fill="${region.accent}"/><rect x="${x + 8}" y="74" width="${Math.max(20, railWidth - 16)}" height="4" fill="${region.horizon}" opacity="0.45"/>`;
    return svg(
      128,
      128,
      [
        ...base,
        '<rect x="34" y="66" width="8" height="44" fill="#b7c0ca"/>',
        '<rect x="86" y="66" width="8" height="44" fill="#b7c0ca"/>',
        barrierBody,
        propAccentMark(region, index),
      ].join("\n"),
      `${region.id} ${prop.id} roadside prop`,
    );
  }
  if (prop.category === "tree") {
    const leaf = prop.id === "wide-tree" ? 32 : 24;
    return svg(
      128,
      128,
      [
        ...base,
        '<rect x="59" y="72" width="10" height="40" fill="#6b4a2e"/>',
        '<rect x="63" y="74" width="4" height="38" fill="#3f2d1f" opacity="0.45"/>',
        `<path d="M64 16 L${64 - leaf} 88 L${64 + leaf} 88 Z" fill="${region.near}"/>`,
        `<path d="M64 8 L${70 - leaf} 66 L${58 + leaf} 66 Z" fill="${region.horizon}" opacity="0.9"/>`,
        `<path d="M64 26 C${44 - (index % 5)} 48 ${48 + (index % 7)} 72 ${64 - leaf + 9} 86" fill="none" stroke="${region.accent}" stroke-width="3" opacity="0.28"/>`,
        `<rect x="${48 + (index % 4) * 2}" y="68" width="10" height="6" fill="${region.accent}" opacity="0.35"/>`,
        propAccentMark(region, index),
      ].join("\n"),
      `${region.id} ${prop.id} roadside prop`,
    );
  }
  const isTower = prop.id === "tower-building";
  const buildingTop = isTower ? 24 : 56;
  const innerTop = buildingTop + 6;
  const buildingHeight = isTower ? 88 : 56;
  const innerHeight = buildingHeight - 12;
  const floors = isTower ? 4 : 2;
  const windows = Array.from({ length: floors * 2 }, (_, i) => {
    const x = 46 + (i % 2) * 24;
    const y = innerTop + 10 + Math.floor(i / 2) * 16;
    return `<rect x="${x}" y="${y}" width="12" height="8" fill="${region.accent}" opacity="0.65"/>`;
  });
  return svg(
    128,
    128,
    [
      ...base,
      `<rect x="34" y="${buildingTop}" width="60" height="${buildingHeight}" fill="${region.horizon}"/>`,
      `<rect x="40" y="${innerTop}" width="48" height="${innerHeight}" fill="${region.near}" opacity="0.82"/>`,
      `<path d="M34 ${buildingTop} L64 ${buildingTop - 10} L94 ${buildingTop} Z" fill="${region.accent}" opacity="0.45"/>`,
      ...windows,
      `<rect x="48" y="${buildingTop + buildingHeight - 12}" width="32" height="8" fill="${region.accent}" opacity="0.6"/>`,
      propAccentMark(region, index),
    ].join("\n"),
    `${region.id} ${prop.id} roadside prop`,
  );
}

function carBodyPath(car: CarSheet): string {
  const noseLeft = car.nose === "wide" ? -30 : car.nose === "blunt" ? -27 : -24;
  const noseRight = car.nose === "wide" ? 30 : car.nose === "blunt" ? 27 : 24;
  const frontY = car.nose === "wedge" ? 13 : 12;
  const shoulder = car.stance === "wide" ? 29 : car.stance === "narrow" ? 24 : 27;
  const roof = car.tail === "long" ? 17 : car.tail === "wide" ? 15 : 12;
  const cabinY = car.tail === "fastback" ? -15 : -14;
  const tailLeft = car.tail === "wide" ? -28 : car.tail === "long" ? -24 : -21;
  const tailRight = car.tail === "wide" ? 28 : car.tail === "long" ? 24 : 21;

  if (car.nose === "wedge") {
    return `M${-shoulder} ${frontY} L${shoulder} ${frontY} L${tailRight} -5 L${roof} ${cabinY} L${-roof} ${cabinY} L${tailLeft} -5 Z`;
  }

  return `M${noseLeft} ${frontY} L${noseRight} ${frontY} L${tailRight} -7 L${roof} ${cabinY} L${-roof} ${cabinY} L${tailLeft} -7 Z`;
}

function carWing(car: CarSheet): string {
  if (car.wing === "none") return "";
  if (car.wing === "ducktail") {
    return `<rect x="-22" y="11" width="44" height="3" fill="${car.secondary}"/><path d="M-24 12 L-18 16 L18 16 L24 12 Z" fill="${car.trim}"/>`;
  }
  if (car.wing === "enduro") {
    return `<rect x="-28" y="10" width="56" height="4" fill="${car.trim}"/><rect x="-23" y="7" width="4" height="8" fill="${car.trim}"/><rect x="19" y="7" width="4" height="8" fill="${car.trim}"/>`;
  }
  return `<rect x="-30" y="8" width="60" height="4" fill="${car.accent}"/><rect x="-24" y="11" width="48" height="3" fill="${car.trim}"/>`;
}

function carDecals(car: CarSheet): string {
  if (car.id === "sparrow_gt") {
    return `<path d="M-18 -5 L18 -5" stroke="${car.accent}" stroke-width="2"/><path d="M-10 6 L10 6" stroke="${car.secondary}" stroke-width="3"/>`;
  }
  if (car.id === "breaker_s") {
    return `<path d="M-22 -3 L-5 9 L22 -3" fill="none" stroke="${car.stripe}" stroke-width="3"/><rect x="-24" y="5" width="10" height="4" fill="${car.secondary}"/>`;
  }
  if (car.id === "vanta_xr") {
    return `<path d="M0 -13 L0 12" stroke="${car.stripe}" stroke-width="2"/><path d="M-18 3 L18 3" stroke="${car.accent}" stroke-width="2"/>`;
  }
  if (car.id === "tempest_r") {
    return `<path d="M-24 6 C-12 -7 10 -7 24 6" fill="none" stroke="${car.stripe}" stroke-width="3"/><path d="M-16 -9 L16 -9" stroke="${car.secondary}" stroke-width="3"/>`;
  }
  if (car.id === "bastion_lm") {
    return `<rect x="-24" y="-3" width="48" height="5" fill="${car.secondary}" opacity="0.85"/><path d="M-18 7 L18 7" stroke="${car.accent}" stroke-width="3"/>`;
  }
  return `<path d="M-20 -8 L-2 11 L20 -8" fill="none" stroke="${car.accent}" stroke-width="3"/><path d="M-13 6 L13 6" stroke="${car.stripe}" stroke-width="2"/>`;
}

function carSheetSvg(car: CarSheet): string {
  const skews = [0, 4, 8, 12, 8, 4, 0, -4, -8, -12, -8, -4];
  const squash = [1, 0.98, 0.95, 0.91, 0.95, 0.98, 1, 0.98, 0.95, 0.91, 0.95, 0.98];
  const stanceScale = car.stance === "wide" ? 1.01 : car.stance === "narrow" ? 0.94 : 0.98;
  const clipDefs = Array.from(
    { length: 48 },
    (_, index) =>
      `<clipPath id="car-cell-${index}"><rect x="${(index % 12) * 64}" y="${Math.floor(index / 12) * 32}" width="64" height="32"/></clipPath>`,
  );
  const damageRows = [
    { y: 16, id: "clean", extra: "" },
    {
      y: 48,
      id: "dented",
      extra: `<path d="M-23 -1 L-17 4 L-21 7" fill="none" stroke="${car.accent}" stroke-width="2" opacity="0.85"/><path d="M12 -8 L20 -3" stroke="${car.trim}" stroke-width="1.5"/>`,
    },
    {
      y: 80,
      id: "battered",
      extra: `<path d="M-24 -2 L-15 5 L-23 8" fill="none" stroke="${car.trim}" stroke-width="2"/><path d="M14 -4 L22 1 L18 7" fill="none" stroke="${car.trim}" stroke-width="2"/><circle cx="-18" cy="-4" r="2" fill="${car.accent}" opacity="0.9"/>`,
    },
    {
      y: 144,
      id: "totaled",
      extra: `<path d="M-27 12 L-18 -5 L-6 8 L8 -7 L25 12" fill="none" stroke="${car.trim}" stroke-width="3"/><path d="M-19 1 L-8 -6 M10 -8 L22 2" stroke="${car.accent}" stroke-width="2"/><path d="M-12 -11 L-2 -5 L10 -12" fill="none" stroke="${car.trim}" stroke-width="2"/>`,
    },
  ];
  const dentedExtra = damageRows.find((row) => row.id === "dented")?.extra ?? "";
  const batteredExtra = damageRows.find((row) => row.id === "battered")?.extra ?? "";
  const frames: string[] = [];
  for (let rowIndex = 0; rowIndex < damageRows.length; rowIndex += 1) {
    const row = damageRows[rowIndex]!;
    for (let i = 0; i < skews.length; i += 1) {
      const clipIndex = rowIndex * skews.length + i;
      frames.push(
        `<g clip-path="url(#car-cell-${clipIndex})"><g transform="translate(${32 + i * 64} ${row.y}) scale(${stanceScale} ${squash[i]}) skewX(${skews[i]})"><use href="#shadow"/><use href="#${row.id}"/></g></g>`,
      );
    }
  }
  return svg(
    768,
    384,
    [
      '<rect width="768" height="384" fill="none"/>',
      '<defs>',
      ...clipDefs,
      '<g id="shadow"><ellipse cx="0" cy="14" rx="27" ry="4" fill="#10151f" opacity="0.58"/></g>',
      `<g id="clean"><path d="${carBodyPath(car)}" fill="${car.body}"/><path d="M-15 -8 L15 -8 L10 4 L-10 4 Z" fill="${car.glass}"/><path d="M-9 -7 L9 -7 L6 3 L-6 3 Z" fill="${car.glass}" opacity="0.8"/><path d="M-24 7 L-12 7 L-12 11 L-24 11 Z" fill="#ff3d38"/><path d="M12 7 L24 7 L24 11 L12 11 Z" fill="#ff3d38"/><path d="M-26 12 L-18 15 L18 15 L26 12 Z" fill="${car.trim}"/>${carWing(car)}${carDecals(car)}<path d="M-20 -10 L-10 -14 L10 -14 L20 -10" fill="none" stroke="${car.stripe}" stroke-width="1.5" opacity="0.8"/></g>`,
      `<g id="dented"><use href="#clean"/>${dentedExtra}<rect x="13" y="7" width="9" height="4" fill="#d72f31"/></g>`,
      `<g id="battered"><use href="#clean"/>${batteredExtra}<rect x="-22" y="7" width="10" height="4" fill="#b83232"/><rect x="13" y="7" width="9" height="4" fill="#b83232"/></g>`,
      `<g id="totaled"><use href="#battered"/>${damageRows.find((row) => row.id === "totaled")?.extra ?? ""}<rect x="-23" y="7" width="11" height="4" fill="#8f2626"/><rect x="12" y="7" width="10" height="4" fill="#8f2626"/></g>`,
      '<g id="brake"><use href="#clean"/><rect x="-24" y="6" width="13" height="6" fill="#ff4a44"/><rect x="11" y="6" width="13" height="6" fill="#ff4a44"/></g>',
      '<g id="nitro"><use href="#clean"/><path d="M-14 15 L0 26 L14 15 Z" fill="#44d7ff" opacity="0.75"/><path d="M-8 15 L0 23 L8 15 Z" fill="#e75cff" opacity="0.8"/></g>',
      '<g id="wet-trail"><path d="M-28 4 L-8 14 L-32 23 Z" fill="#d8f4ff" opacity="0.55"/><path d="M28 4 L8 14 L32 23 Z" fill="#d8f4ff" opacity="0.55"/><path d="M-22 13 L-3 19 M22 13 L3 19" stroke="#9fd7ef" stroke-width="2" opacity="0.7"/></g>',
      '<g id="snow-trail"><path d="M-24 9 L24 9 L34 24 L-34 24 Z" fill="#edf7ff" opacity="0.64"/><circle cx="-18" cy="17" r="2" fill="#ffffff" opacity="0.7"/><circle cx="0" cy="20" r="2" fill="#ffffff" opacity="0.7"/><circle cx="17" cy="16" r="2" fill="#ffffff" opacity="0.7"/></g>',
      "</defs>",
      ...frames,
      '<g transform="translate(32 112)"><use href="#shadow"/><use href="#brake"/></g>',
      '<g transform="translate(96 112)"><use href="#shadow"/><use href="#nitro"/></g>',
      '<g transform="translate(32 176)"><use href="#wet-trail"/></g>',
      '<g transform="translate(96 176)"><use href="#snow-trail"/></g>',
      `<text x="704" y="360" text-anchor="middle" font-family="monospace" font-size="16" font-weight="700" fill="${car.accent}">${car.name}</text>`,
    ].join("\n"),
    `${car.name} production car sprite sheet`,
  );
}

function hudIconSvg(id: string): string {
  const label = id.slice(0, 2).toUpperCase();
  return svg(
    64,
    64,
    [
      '<rect x="4" y="4" width="56" height="56" rx="6" fill="#101827"/>',
      '<rect x="8" y="8" width="48" height="48" rx="4" fill="#26364d"/>',
      '<circle cx="32" cy="29" r="14" fill="#f5d45f"/>',
      `<text x="32" y="38" text-anchor="middle" font-family="monospace" font-size="16" font-weight="700" fill="#101827">${label}</text>`,
    ].join("\n"),
  );
}

function effectSvg(effect: string): string {
  return svg(
    256,
    256,
    [
      '<rect width="256" height="256" fill="none"/>',
      '<circle cx="64" cy="64" r="42" fill="#ffffff" opacity="0.38"/>',
      '<circle cx="144" cy="82" r="28" fill="#f5d45f" opacity="0.55"/>',
      '<path d="M42 184 C82 142 118 218 162 162 C184 135 204 148 226 124" fill="none" stroke="#dce8f5" stroke-width="14" stroke-linecap="round" opacity="0.72"/>',
      `<text x="128" y="235" text-anchor="middle" font-family="monospace" font-size="18" font-weight="700" fill="#ffffff">${effect.toUpperCase()}</text>`,
    ].join("\n"),
  );
}

function menuBackgroundSvg(menu: (typeof MENU_BACKGROUNDS)[number]): string {
  const region = REGIONS.find((entry) => entry.id === menu.region);
  if (region === undefined) throw new Error(`Unknown menu background region: ${menu.region}`);
  const scene = menuSceneSvg(menu.id, region);
  return svg(
    1920,
    1080,
    [
      `<rect width="1920" height="1080" fill="${region.sky}"/>`,
      `<path d="M0 330 L220 150 L420 330 L690 176 L940 330 L1180 130 L1410 330 L1660 170 L1920 290 L1920 520 L0 520 Z" fill="${region.horizon}" opacity="0.62"/>`,
      `<path d="M0 462 C260 410 500 478 730 420 C1020 350 1230 450 1460 398 C1670 354 1800 396 1920 360 L1920 650 L0 650 Z" fill="${region.near}" opacity="0.82"/>`,
      '<rect x="0" y="636" width="1920" height="444" fill="#0b1019" opacity="0.42"/>',
      `<path d="M-120 1080 C260 870 590 790 960 812 C1320 832 1600 902 2040 790 L2040 1080 Z" fill="#172033" opacity="0.72"/>`,
      `<path d="M720 1080 L900 642 L1020 642 L1200 1080 Z" fill="#535b60" opacity="0.82"/>`,
      `<path d="M926 1080 L955 642 L965 642 L994 1080 Z" fill="${region.accent}" opacity="0.76"/>`,
      `<path d="M100 218 C330 174 540 230 760 188 C980 146 1200 230 1420 188 C1630 148 1780 170 1920 144 L1920 216 C1710 240 1500 222 1270 246 C980 276 790 214 520 260 C330 292 180 260 100 282 Z" fill="${region.accent}" opacity="0.12"/>`,
      `<rect x="112" y="118" width="420" height="16" fill="${region.accent}" opacity="0.64"/>`,
      `<rect x="112" y="154" width="260" height="8" fill="${region.accent}" opacity="0.28"/>`,
      scene,
    ].join("\n"),
    `${menu.label.toLowerCase()} production menu background`,
  );
}

function menuSceneSvg(id: MenuBackgroundId, region: RegionArt): string {
  const car = `<g transform="translate(820 770) scale(1.55)"><path d="M30 96 L46 42 L82 18 L130 18 L166 42 L182 96 Z" fill="${region.accent}"/><path d="M66 38 L96 28 L132 38 L144 62 L54 62 Z" fill="#101827"/><rect x="52" y="82" width="34" height="12" fill="#ff4d3d"/><rect x="126" y="82" width="34" height="12" fill="#ff4d3d"/><path d="M24 100 L188 100 L176 112 L36 112 Z" fill="#101827" opacity="0.65"/></g>`;
  if (id === "title") {
    return [
      '<rect x="620" y="620" width="680" height="46" fill="#d7dde6" opacity="0.42"/>',
      car,
      `<path d="M640 704 C790 654 1050 654 1260 704" fill="none" stroke="${region.accent}" stroke-width="18" opacity="0.55"/>`,
      '<rect x="710" y="548" width="500" height="28" fill="#d7dde6" opacity="0.78"/>',
    ].join("\n");
  }
  if (id === "world") {
    return [
      `<path d="M520 690 C650 590 790 640 900 560 C1030 466 1190 560 1390 494" fill="none" stroke="${region.accent}" stroke-width="28" opacity="0.72"/>`,
      '<circle cx="520" cy="690" r="22" fill="#f5d45f"/>',
      '<circle cx="900" cy="560" r="22" fill="#f5d45f"/>',
      '<circle cx="1390" cy="494" r="22" fill="#f5d45f"/>',
      '<rect x="1180" y="740" width="280" height="90" fill="#26364d" opacity="0.9"/>',
    ].join("\n");
  }
  if (id === "garage") {
    return [
      '<rect x="420" y="530" width="1080" height="350" fill="#1e293b" opacity="0.88"/>',
      '<rect x="500" y="610" width="300" height="210" fill="#101827"/>',
      '<rect x="840" y="610" width="300" height="210" fill="#101827"/>',
      '<rect x="1180" y="610" width="240" height="210" fill="#101827"/>',
      car,
      `<rect x="470" y="546" width="980" height="18" fill="${region.accent}" opacity="0.7"/>`,
    ].join("\n");
  }
  if (id === "race-prep") {
    return [
      '<rect x="460" y="612" width="1000" height="150" fill="#d7dde6" opacity="0.2"/>',
      `<rect x="540" y="654" width="840" height="20" fill="${region.accent}" opacity="0.74"/>`,
      '<rect x="610" y="700" width="90" height="88" fill="#26364d"/>',
      '<rect x="1220" y="700" width="90" height="88" fill="#26364d"/>',
      car,
    ].join("\n");
  }
  if (id === "results") {
    return [
      '<rect x="760" y="702" width="400" height="126" fill="#d7dde6" opacity="0.24"/>',
      '<rect x="866" y="610" width="190" height="218" fill="#d7dde6" opacity="0.34"/>',
      `<rect x="880" y="584" width="160" height="24" fill="${region.accent}" opacity="0.8"/>`,
      '<rect x="604" y="670" width="190" height="158" fill="#d7dde6" opacity="0.24"/>',
      '<rect x="1126" y="690" width="190" height="138" fill="#d7dde6" opacity="0.22"/>',
    ].join("\n");
  }
  if (id === "daily") {
    return [
      '<rect x="590" y="580" width="740" height="260" fill="#101827" opacity="0.72"/>',
      `<path d="M640 766 C760 690 840 750 950 646 C1060 544 1180 608 1280 546" fill="none" stroke="${region.accent}" stroke-width="20" opacity="0.78"/>`,
      '<circle cx="950" cy="646" r="46" fill="#f5d45f"/>',
      '<rect x="704" y="614" width="160" height="18" fill="#d7dde6" opacity="0.52"/>',
      '<rect x="1058" y="732" width="180" height="18" fill="#d7dde6" opacity="0.44"/>',
    ].join("\n");
  }
  if (id === "options") {
    return [
      '<rect x="610" y="548" width="700" height="320" fill="#101827" opacity="0.76"/>',
      `<rect x="680" y="628" width="560" height="24" fill="${region.accent}" opacity="0.66"/>`,
      '<rect x="680" y="704" width="430" height="24" fill="#d7dde6" opacity="0.5"/>',
      '<rect x="680" y="780" width="500" height="24" fill="#d7dde6" opacity="0.38"/>',
      '<circle cx="1250" cy="640" r="32" fill="#f5d45f"/>',
      '<circle cx="1128" cy="716" r="32" fill="#f5d45f"/>',
      '<circle cx="1200" cy="792" r="32" fill="#f5d45f"/>',
    ].join("\n");
  }
  if (id === "loading") {
    return [
      '<rect x="520" y="650" width="880" height="70" fill="#d7dde6" opacity="0.22"/>',
      '<rect x="620" y="730" width="680" height="42" fill="#d7dde6" opacity="0.16"/>',
      `<rect x="720" y="808" width="480" height="24" fill="${region.accent}" opacity="0.78"/>`,
      '<circle cx="1280" cy="840" r="24" fill="#f5d45f"/>',
      car,
    ].join("\n");
  }
  throw new Error(`Unknown menu scene id: ${id satisfies never}`);
}

for (const region of REGIONS) {
  for (const layer of ["sky", "mountains", "hills"] as const) {
    const relPath = `public/art/backdrops/${region.id}/${layer}.svg`;
    writeTextFile(relPath, backdropSvg(region, layer));
    addManifest(`backdrop:${region.id}:${layer}`, relPath.slice("public/".length));
  }
}

const starterCarSheet = CAR_SHEETS.find((car) => car.id === "sparrow_gt");
if (!starterCarSheet) {
  throw new Error("Missing Sparrow GT car sheet");
}

writeTextFile("public/art/cars/sparrow.svg", carSheetSvg(starterCarSheet));

for (const car of CAR_SHEETS) {
  const relPath = `public/art/cars/${car.id}.svg`;
  writeTextFile(relPath, carSheetSvg(car));
  addManifest(`car:${car.id}:sprite-sheet`, relPath.slice("public/".length), {
    license: "CC-BY-4.0",
    source: CAR_SOURCE,
    originality: CAR_ORIGINALITY,
  });
}

writeTextFile("public/art/roadside/temperate.svg", roadsideSvg());
addManifest("roadside:temperate", "art/roadside/temperate.svg", {
  license: "CC-BY-4.0",
  source: ROADSIDE_SOURCE,
  originality: ROADSIDE_ORIGINALITY,
});

for (const region of REGIONS) {
  for (const [i, prop] of ROADSIDE_PROPS.entries()) {
    const relPath = `public/art/roadside/${region.id}/${prop.id}.svg`;
    writeTextFile(relPath, roadsidePropSvg(region, prop, i));
    addManifest(`roadside:${region.id}:${prop.id}`, relPath.slice("public/".length), {
      license: "CC-BY-4.0",
      source: ROADSIDE_SOURCE,
      originality: ROADSIDE_ORIGINALITY,
    });
  }
}

for (const icon of HUD_ICONS) {
  const relPath = `public/art/hud/${icon}.svg`;
  writeTextFile(relPath, hudIconSvg(icon));
  addManifest(`hud:${icon}`, relPath.slice("public/".length));
}

for (const effect of EFFECTS) {
  const relPath = `public/art/effects/${effect}.svg`;
  writeTextFile(relPath, effectSvg(effect));
  addManifest(`effect:${effect}`, relPath.slice("public/".length));
}

for (const menu of MENU_BACKGROUNDS) {
  const relPath = `public/art/menu/${menu.id}.svg`;
  writeTextFile(relPath, menuBackgroundSvg(menu));
  addManifest(`menu:${menu.id}:background`, relPath.slice("public/".length), {
    license: "CC-BY-4.0",
    source: MENU_SOURCE,
    originality: MENU_ORIGINALITY,
  });
}

manifest.sort((a, b) => a.src.localeCompare(b.src));
writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + "\n", "utf8");
