import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

interface AudioManifestEntry {
  id: string;
  src: string;
  path: string;
  kind: "audio";
  license: "CC0";
  source: string;
  originality: string;
  date: string;
  durationSeconds: number;
  sampleRate: number;
}

interface AudioAssetSpec {
  id: string;
  path: string;
  durationSeconds: number;
  frequencies: readonly number[];
  volume: number;
}

const ROOT = process.cwd();
const SAMPLE_RATE = 48_000;
const GENERATED_DATE = "2026-04-29";
const SOURCE = "agent-authored placeholder generated by scripts/generate-placeholder-audio.ts";
const ORIGINALITY =
  "Original procedural placeholder audio authored for VibeGear2. It does not copy a commercial game soundtrack, melody, recording, sample library, or sound mark.";

const MUSIC_REGIONS = [
  "title",
  "velvet-coast",
  "iron-borough",
  "ember-steppe",
  "breakwater-isles",
  "glass-ridge",
  "neon-meridian",
  "moss-frontier",
  "crown-circuit",
] as const;

const RACE_MUSIC_REGIONS = MUSIC_REGIONS.filter((id) => id !== "title");

const MUSIC_INTENSITY_LAYERS = ["drive", "lead"] as const;

const SFX_IDS = [
  "ui-hover",
  "ui-confirm",
  "ui-back",
  "countdown-3",
  "countdown-2",
  "countdown-1",
  "countdown-go",
  "impact-light",
  "impact-heavy",
  "nitro-on",
  "nitro-off",
  "gear-up",
  "gear-down",
  "puddle-splash",
  "grass-skid",
  "brake-screech",
  "collision-crunch",
  "horn",
  "checkpoint",
  "finish",
  "damage-warn",
  "record-set",
] as const;

const WEATHER_IDS = ["rain-loop", "fog-wind-loop", "snow-loop", "heavy-rain-loop"] as const;

function musicSpec(id: string, index: number): AudioAssetSpec {
  const root = 110 + index * 17;
  return {
    id: `music:${id}`,
    path: `audio/music/${id}.opus`,
    durationSeconds: id === "title" ? 6 : 4,
    frequencies: [root, root * 1.5, root * 2],
    volume: 0.18,
  };
}

function musicIntensityLayerSpec(
  region: string,
  regionIndex: number,
  layer: (typeof MUSIC_INTENSITY_LAYERS)[number],
  layerIndex: number,
): AudioAssetSpec {
  const root = 150 + regionIndex * 19 + layerIndex * 31;
  const layerGain = layer === "drive" ? 0.11 : 0.09;
  return {
    id: `music-layer:${region}:${layer}`,
    path: `audio/music/stems/${region}-${layer}.opus`,
    durationSeconds: 4,
    frequencies:
      layer === "drive"
        ? [root, root * 1.25, root * 1.75]
        : [root * 1.5, root * 2, root * 2.5],
    volume: layerGain,
  };
}

function sfxSpec(id: string, index: number): AudioAssetSpec {
  const base = 220 + index * 23;
  const durationSeconds = id.startsWith("impact") || id.includes("crunch") ? 0.55 : 0.32;
  return {
    id: `sfx:${id}`,
    path: `audio/sfx/${id}.opus`,
    durationSeconds,
    frequencies: id.includes("countdown") ? [440 + index * 55] : [base, base * 1.25],
    volume: 0.26,
  };
}

function weatherSpec(id: string, index: number): AudioAssetSpec {
  const base = 150 + index * 41;
  return {
    id: `weather:${id}`,
    path: `audio/weather/${id}.opus`,
    durationSeconds: 4,
    frequencies: [base, base * 1.33],
    volume: 0.14,
  };
}

function ensureParent(relPath: string): void {
  mkdirSync(path.dirname(path.join(ROOT, "public", relPath)), { recursive: true });
}

function lavfi(spec: AudioAssetSpec): string {
  const inputs = spec.frequencies.map(
    (frequency) =>
      `sine=frequency=${Math.round(frequency)}:duration=${spec.durationSeconds}:sample_rate=${SAMPLE_RATE}`,
  );
  const labels = spec.frequencies.map((_, index) => `[${index}:a]`).join("");
  const mix = `${labels}amix=inputs=${spec.frequencies.length}:normalize=1,volume=${spec.volume},afade=t=in:st=0:d=0.02,afade=t=out:st=${Math.max(0, spec.durationSeconds - 0.08)}:d=0.08[a]`;
  return `${inputs.map((input) => `-f lavfi -i ${input}`).join(" ")} -filter_complex ${mix}`;
}

function generate(spec: AudioAssetSpec): AudioManifestEntry {
  ensureParent(spec.path);
  const outputPath = path.join(ROOT, "public", spec.path);
  const args = [
    "-y",
    "-v",
    "error",
    ...lavfi(spec).split(" "),
    "-map",
    "[a]",
    "-c:a",
    "libopus",
    "-b:a",
    "24k",
    "-application",
    "audio",
    "-map_metadata",
    "-1",
    outputPath,
  ];
  execFileSync("ffmpeg", args, { stdio: "inherit" });
  return {
    id: spec.id,
    src: "/" + spec.path,
    path: spec.path,
    kind: "audio",
    license: "CC0",
    source: SOURCE,
    originality: ORIGINALITY,
    date: GENERATED_DATE,
    durationSeconds: spec.durationSeconds,
    sampleRate: SAMPLE_RATE,
  };
}

const specs: AudioAssetSpec[] = [
  ...MUSIC_REGIONS.map(musicSpec),
  ...RACE_MUSIC_REGIONS.flatMap((region, regionIndex) =>
    MUSIC_INTENSITY_LAYERS.map((layer, layerIndex) =>
      musicIntensityLayerSpec(region, regionIndex, layer, layerIndex),
    ),
  ),
  ...SFX_IDS.map(sfxSpec),
  ...WEATHER_IDS.map(weatherSpec),
];

const manifest = specs.map(generate).sort((a, b) => a.src.localeCompare(b.src));
writeFileSync(
  path.join(ROOT, "public", "audio", "manifest.json"),
  JSON.stringify(manifest, null, 2) + "\n",
  "utf8",
);
