import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

interface ManifestEntry {
  id: string;
  src: string;
  path: string;
  kind: "image";
  license: "CC0" | "CC-BY-4.0";
  source: string;
  originality: string;
  date: string;
}

interface RegionArt {
  id: string;
  sky: string;
  horizon: string;
  near: string;
  accent: string;
}

const ROOT = process.cwd();
const PUBLIC_ART_DIR = path.join(ROOT, "public", "art");
const MANIFEST_PATH = path.join(ROOT, "public", "art.manifest.json");
const GENERATED_DATE = "2026-04-29";
const SOURCE = "agent-authored placeholder generated by scripts/generate-placeholder-art.ts";
const ORIGINALITY =
  "Original geometric placeholder art authored for VibeGear2. It does not trace or copy a commercial game asset, real vehicle, logo, or manufacturer design.";

const REGIONS: readonly RegionArt[] = [
  { id: "velvet-coast", sky: "#17325c", horizon: "#2f6f54", near: "#285d2b", accent: "#9cc9ff" },
  { id: "iron-borough", sky: "#1d2937", horizon: "#535b60", near: "#343a40", accent: "#f5cf69" },
  { id: "ember-steppe", sky: "#40263b", horizon: "#9b4b32", near: "#5f3d22", accent: "#ffba6b" },
  { id: "breakwater-isles", sky: "#12304a", horizon: "#326a84", near: "#1f5e45", accent: "#a7e3ff" },
  { id: "glass-ridge", sky: "#223a56", horizon: "#8da8bc", near: "#4e6b7b", accent: "#d8f4ff" },
  { id: "neon-meridian", sky: "#151833", horizon: "#4c3d79", near: "#22324f", accent: "#ff5bd6" },
  { id: "moss-frontier", sky: "#17352b", horizon: "#37694b", near: "#204f32", accent: "#c2e879" },
  { id: "crown-circuit", sky: "#1c2345", horizon: "#55608a", near: "#2e355b", accent: "#ffd85a" },
];

const HUD_ICONS = [
  "cash",
  "repair",
  "engine",
  "gearbox",
  "dry-tire",
  "wet-tire",
  "nitro",
  "armor",
  "visibility",
  "grip",
  "tour-standings",
] as const;

const EFFECTS = ["flash", "dust", "sparks", "rain", "fog", "snow"] as const;

const manifest: ManifestEntry[] = [
  {
    id: "sparrow-car-sprite-atlas",
    src: "/art/cars/sparrow.svg",
    path: "art/cars/sparrow.svg",
    kind: "image",
    license: "CC-BY-4.0",
    source: "original by VibeGear2 project contributors in this repository",
    originality:
      "Original stylized compact sports coupe sprite sheet drawn for VibeGear2 on 2026-04-27. It uses simple geometric shapes and does not trace or copy a commercial game asset, real vehicle, logo, or manufacturer design.",
    date: "2026-04-27",
  },
];

function writeTextFile(relPath: string, contents: string): void {
  const abs = path.join(ROOT, relPath);
  mkdirSync(path.dirname(abs), { recursive: true });
  writeFileSync(abs, contents, "utf8");
}

function addManifest(id: string, relPath: string): void {
  manifest.push({
    id,
    src: "/" + relPath,
    path: relPath,
    kind: "image",
    license: "CC0",
    source: SOURCE,
    originality: ORIGINALITY,
    date: GENERATED_DATE,
  });
}

function svg(width: number, height: number, body: string): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="VibeGear2 placeholder art">`,
    body,
    "</svg>",
    "",
  ].join("\n");
}

function backdropSvg(region: RegionArt, layer: "sky" | "mountains" | "hills"): string {
  if (layer === "sky") {
    return svg(
      1920,
      540,
      [
        `<rect width="1920" height="540" fill="${region.sky}"/>`,
        `<path d="M0 270 L220 120 L430 270 L650 150 L900 270 L1160 110 L1390 270 L1660 130 L1920 250 L1920 540 L0 540 Z" fill="${region.horizon}" opacity="0.55"/>`,
        `<rect x="0" y="505" width="1920" height="35" fill="${region.accent}" opacity="0.18"/>`,
      ].join("\n"),
    );
  }
  if (layer === "mountains") {
    return svg(
      1920,
      220,
      [
        `<rect width="1920" height="220" fill="none"/>`,
        `<path d="M0 190 L150 90 L300 190 L500 70 L760 190 L970 85 L1220 190 L1460 60 L1740 190 L1920 105 L1920 220 L0 220 Z" fill="${region.horizon}"/>`,
        `<path d="M0 205 C260 170 470 200 690 165 C920 130 1120 180 1340 145 C1580 115 1740 165 1920 130 L1920 220 L0 220 Z" fill="${region.near}" opacity="0.62"/>`,
      ].join("\n"),
    );
  }
  return svg(
    1920,
    180,
    [
      `<rect width="1920" height="180" fill="none"/>`,
      `<path d="M0 120 C210 92 360 124 530 105 C720 82 880 128 1080 98 C1310 66 1500 118 1680 92 C1810 74 1880 82 1920 76 L1920 180 L0 180 Z" fill="${region.near}"/>`,
      `<rect x="0" y="154" width="1920" height="26" fill="${region.accent}" opacity="0.22"/>`,
    ].join("\n"),
  );
}

function roadsideSvg(): string {
  return svg(
    512,
    256,
    [
      '<rect width="512" height="256" fill="none"/>',
      '<rect x="6" y="8" width="20" height="54" fill="#d7dde6"/>',
      '<rect x="2" y="0" width="28" height="12" fill="#fff275"/>',
      '<rect x="42" y="8" width="20" height="54" fill="#d7dde6"/>',
      '<rect x="38" y="0" width="28" height="12" fill="#fff275"/>',
      '<path d="M96 8 L62 96 L132 96 Z" fill="#1f7a45"/>',
      '<rect x="92" y="72" width="8" height="24" fill="#6b4a2e"/>',
      '<path d="M160 2 L124 96 L198 96 Z" fill="#2f8a52"/>',
      '<rect x="156" y="72" width="8" height="24" fill="#6b4a2e"/>',
      '<path d="M224 12 L190 96 L260 96 Z" fill="#1d6e3b"/>',
      '<rect x="220" y="72" width="8" height="24" fill="#6b4a2e"/>',
      '<rect x="0" y="104" width="14" height="24" fill="#c4cad3"/>',
      '<rect x="34" y="110" width="42" height="18" fill="#8e9299"/>',
      '<rect x="82" y="106" width="42" height="22" fill="#7b8087"/>',
      '<rect x="260" y="0" width="10" height="128" fill="#d7dde6"/>',
      '<rect x="248" y="0" width="34" height="10" fill="#fff275"/>',
      '<rect x="310" y="42" width="76" height="58" fill="#45515c"/>',
      '<rect x="322" y="54" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="350" y="54" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="328" y="76" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="358" y="76" width="14" height="12" fill="#7ea0b8"/>',
      '<rect x="410" y="72" width="88" height="18" fill="#bdc3ca"/>',
      '<rect x="418" y="88" width="12" height="40" fill="#bdc3ca"/>',
      '<rect x="478" y="88" width="12" height="40" fill="#bdc3ca"/>',
    ].join("\n"),
  );
}

function hudIconSvg(id: string): string {
  const label = id.slice(0, 2).toUpperCase();
  return svg(
    64,
    64,
    [
      '<rect x="4" y="4" width="56" height="56" rx="6" fill="#101827"/>',
      '<rect x="8" y="8" width="48" height="48" rx="4" fill="#26364d"/>',
      '<circle cx="32" cy="29" r="14" fill="#f5d45f"/>',
      `<text x="32" y="38" text-anchor="middle" font-family="monospace" font-size="16" font-weight="700" fill="#101827">${label}</text>`,
    ].join("\n"),
  );
}

function effectSvg(effect: string): string {
  return svg(
    256,
    256,
    [
      '<rect width="256" height="256" fill="none"/>',
      '<circle cx="64" cy="64" r="42" fill="#ffffff" opacity="0.38"/>',
      '<circle cx="144" cy="82" r="28" fill="#f5d45f" opacity="0.55"/>',
      '<path d="M42 184 C82 142 118 218 162 162 C184 135 204 148 226 124" fill="none" stroke="#dce8f5" stroke-width="14" stroke-linecap="round" opacity="0.72"/>',
      `<text x="128" y="235" text-anchor="middle" font-family="monospace" font-size="18" font-weight="700" fill="#ffffff">${effect.toUpperCase()}</text>`,
    ].join("\n"),
  );
}

for (const region of REGIONS) {
  for (const layer of ["sky", "mountains", "hills"] as const) {
    const relPath = `public/art/backdrops/${region.id}/${layer}.svg`;
    writeTextFile(relPath, backdropSvg(region, layer));
    addManifest(`backdrop:${region.id}:${layer}`, relPath.slice("public/".length));
  }
}

writeTextFile("public/art/roadside/temperate.svg", roadsideSvg());
addManifest("roadside:temperate", "art/roadside/temperate.svg");

for (const icon of HUD_ICONS) {
  const relPath = `public/art/hud/${icon}.svg`;
  writeTextFile(relPath, hudIconSvg(icon));
  addManifest(`hud:${icon}`, relPath.slice("public/".length));
}

for (const effect of EFFECTS) {
  const relPath = `public/art/effects/${effect}.svg`;
  writeTextFile(relPath, effectSvg(effect));
  addManifest(`effect:${effect}`, relPath.slice("public/".length));
}

manifest.sort((a, b) => a.src.localeCompare(b.src));
writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + "\n", "utf8");
